[build]
  publish = "."
  command = "npm run build"

# Cache static assets aggressively
[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
